version: '3'
services:
  code-server-python:
    container_name: code-server-python
    build:
      context: ./
      dockerfile: Dockerfile
    image: code-server-python:v1
    security_opt: ['seccomp:unconfined']
    environment: 
      - PASSWORD=123
      - SERVICE_URL=https://marketplace.visualstudio.com/_apis/public/gallery/
      - ITEM_URL=https://marketplace.visualstudio.com/items
    ulimits:
      memlock:
        soft: -1
        hard: -1
    command: --proxy-server=socks5://192.168.1.8:1080
    deploy:
      resources:
        limits:
          memory: 2G
    volumes:
      - ${HOME}/.local/share/code-server:/root/.local/share/code-server
      - ${HOME}/python-projects:/root/project
    ports:
      - "8080:8080"
